<?php
/*
Openfire Integration
Author: Sebijk
Website: http://www.sebijk.com
Download at: http://www.mybbcoder.info
*/

if(!defined("IN_MYBB"))
{
    die("This file cannot be accessed directly.");
}

$plugins->add_hook("member_do_register_end", "openfire");

function openfire_info()
{
	return array(
		"name"		    => "Openfire-Integration",
		"description"	=> "Integrate Openfire to MyBulletinBoard.",
		"website"		=> "http://www.mybbcoder.info",
		"author"		=> "Home of the Sebijk.com",
		"authorsite"	=> "http://www.sebijk.com",
		"version"		=> "1.0.0 Beta 2",
		"guid" 			=> "1661a1799814c5059bcd80ec0688d26c",
		"compatibility" => "*"
	);
}

function openfire_activate()
{
global $db, $mybb;

$openfire_group = array(
		"gid"			=> "NULL",
		"name"			=> "openfire_integration",
		"title"			=> "Openfire Integration",
		"description"	=> "Settings for Openfire.",
		"disporder"		=> "3",
		"isdefault"		=> "no",
	);
	
	$db->insert_query("settinggroups", $openfire_group);
	$gid = $db->insert_id();
	
	
	$openfire_setting_1 = array(
		"sid"			=> "NULL",
		"name"			=> "openfire_host",
		"title"			=> "Openfire-Hostdomain",
		"description"	=> "Please enter the Hostname of the Openfire Server",
		"optionscode"	=> "text",
		"value"			=> 'localhost',
		"disporder"		=> '1',
		"gid"			=> intval($gid),
	);
	
	$openfire_setting_2 = array(
		"sid"			=> "NULL",
		"name"			=> "openfire_secretkey",
		"title"			=> "Openfire Secret Key",
		"description"	=> "Your Openfire Secret Key.",
		"optionscode"	=> "text",
		"value"			=> "",
		"disporder"		=> '2',
		"gid"			=> intval($gid),
	);
	
	$db->insert_query("settings", $openfire_setting_1);
	$db->insert_query("settings", $openfire_setting_2);
	rebuild_settings();

}


function openfire_deactivate()
{
	global $db;

	$db->query("DELETE FROM ".TABLE_PREFIX."settings WHERE name='openfire_host'");
	$db->query("DELETE FROM ".TABLE_PREFIX."settings WHERE name='openfire_secretkey'");
	$db->query("DELETE FROM ".TABLE_PREFIX."settinggroups WHERE name='openfire_integration'");
	rebuild_settings();


}


function openfire()
{
  global $mybb, $user;
$sendjabber_register = file_get_contents("https://".$mybb->settings['openfire_host'].":9091/plugins/userService/userservice?type=add&secret=".$mybb->settings['openfire_secretkey']."&username=".utf8_encode(rawurlencode($mybb->input['username']))."&password=".utf8_encode(rawurlencode($mybb->input['password']))."&email=".utf8_encode(rawurlencode($mybb->input['email'])));
}


if(!function_exists("rebuild_settings"))
{
	function rebuild_settings()
	{
		global $db;
		$query = $db->query("SELECT * FROM ".TABLE_PREFIX."settings ORDER BY title ASC");
		while($setting = $db->fetch_array($query))
		{
			$setting['value'] = addslashes($setting['value']);
			$settings .= "\$settings['".$setting['name']."'] = \"".$setting['value']."\";\n";
		}
		$settings = "<?php\n/*********************************\ \n  DO NOT EDIT THIS FILE, PLEASE USE\n  THE SETTINGS EDITOR\n\*********************************/\n\n$settings\n?>";
		$file = fopen(MYBB_ROOT. "inc/settings.php", "w");
		fwrite($file, $settings);
		fclose($file);
	}
}
?>